import { Product, Order } from '../App';

export const mockProducts: Product[] = [
  // === KATEGORI IMMUNITY (5 produk) ===
  {
    id: '1',
    name: 'Kunyit Bubuk Organik',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1626025599030-9af1661695f4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0dXJtZXJpYyUyMHBvd2RlciUyMHllbGxvdyUyMGdvbGRlbnxlbnwxfHx8fDE3NjQ1NjA3NDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'immunity',
    farmer: {
      name: 'Pak Budi Santoso',
      location: 'Yogyakarta',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Kunyit organik berkualitas tinggi yang ditanam tanpa pestisida. Dipanen segar dan dikeringkan dengan metode tradisional untuk menjaga kualitas.',
    benefits: [
      'Meningkatkan sistem imun',
      'Anti-inflamasi alami',
      'Menjaga kesehatan pencernaan',
      'Kaya antioksidan',
    ],
    usage: 'Seduh 1 sendok teh kunyit bubuk dengan air hangat. Minum 1-2 kali sehari, bisa ditambah madu.',
    rating: 4.8,
    reviews: 124,
    stock: 50,
  },
  {
    id: '3',
    name: 'Daun Kelor Kering',
    price: 28000,
    image: 'https://images.unsplash.com/photo-1564072699250-5af00a5e6487?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxtb3JpbmdhJTIwbGVhdmVzJTIwZHJpZWQlMjBncmVlbnxlbnwxfHx8fDE3NjQ1NjA3NDZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'immunity',
    farmer: {
      name: 'Pak Ahmad Fauzi',
      location: 'Bogor, Jawa Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Daun kelor superfood kaya nutrisi. Dipanen dari pohon kelor organik dan dikeringkan higienis.',
    benefits: [
      'Kaya vitamin dan mineral',
      'Meningkatkan energi',
      'Menurunkan gula darah',
      'Menjaga kesehatan jantung',
    ],
    usage: 'Seduh 1 sendok teh daun kelor dengan air panas seperti teh. Minum 2 kali sehari.',
    rating: 4.7,
    reviews: 156,
    stock: 75,
  },
  {
    id: '6',
    name: 'Sambiloto Kering',
    price: 30000,
    image: 'https://images.unsplash.com/photo-1760768334700-f2ccf065f211?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbmRyb2dyYXBoaXMlMjBiaXR0ZXIlMjBsZWF2ZXN8ZW58MXx8fHwxNzY0NTYwNzQ2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'immunity',
    farmer: {
      name: 'Pak Hendra Gunawan',
      location: 'Surabaya, Jawa Timur',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Sambiloto kualitas premium, dipanen pada waktu yang tepat untuk khasiat maksimal.',
    benefits: [
      'Meningkatkan daya tahan tubuh',
      'Menurunkan demam',
      'Antibakteri alami',
      'Menjaga gula darah',
    ],
    usage: 'Seduh 5-7 lembar sambiloto kering dengan air panas. Minum 1 kali sehari.',
    rating: 4.4,
    reviews: 67,
    stock: 45,
  },
  {
    id: '7',
    name: 'Mengkudu Bubuk Premium',
    price: 42000,
    image: 'https://images.unsplash.com/photo-1605879883262-0cd26b362f54?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxub25pJTIwZnJ1aXQlMjBtb3JpbmRhJTIwZHJpZWR8ZW58MXx8fHwxNzY0NTYwOTE5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'immunity',
    farmer: {
      name: 'Ibu Kartini Dewi',
      location: 'Bali',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Mengkudu (Noni) asli Bali yang dikeringkan dan dibuat bubuk untuk kemudahan konsumsi. Terkenal sebagai raja herbal untuk imunitas.',
    benefits: [
      'Meningkatkan sistem kekebalan tubuh',
      'Antioksidan tinggi',
      'Menurunkan tekanan darah tinggi',
      'Membantu melawan infeksi',
    ],
    usage: 'Campurkan 1/2 sendok teh mengkudu bubuk dengan air atau jus buah. Minum 1 kali sehari setelah makan.',
    rating: 4.6,
    reviews: 98,
    stock: 35,
  },
  {
    id: '8',
    name: 'Bawang Putih Tunggal Kering',
    price: 55000,
    image: 'https://images.unsplash.com/photo-1580618900732-3f5835efe4b6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzaW5nbGUlMjBnYXJsaWMlMjBjbG92ZSUyMGJ1bGJ8ZW58MXx8fHwxNzY0NTYwOTE3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'immunity',
    farmer: {
      name: 'Pak Bambang Wijaya',
      location: 'Tawangmangu, Jawa Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Bawang putih tunggal langka dari dataran tinggi Tawangmangu. Memiliki khasiat 7x lebih kuat dibanding bawang putih biasa.',
    benefits: [
      'Antibiotik alami super kuat',
      'Menurunkan kolesterol dan tekanan darah',
      'Mencegah kanker',
      'Meningkatkan stamina dan imunitas',
    ],
    usage: 'Konsumsi 1-2 siung bawang putih tunggal kering setiap pagi sebelum makan. Bisa dikunyah atau ditelan langsung.',
    rating: 4.9,
    reviews: 143,
    stock: 25,
  },

  // === KATEGORI ENERGY (5 produk) ===
  {
    id: '2',
    name: 'Jahe Merah Kering',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1758738880738-8f662ac47e4f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZWQlMjBnaW5nZXIlMjByb290JTIwZnJlc2h8ZW58MXx8fHwxNzY0NTYwNzQ2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'energy',
    farmer: {
      name: 'Ibu Siti Rahayu',
      location: 'Malang, Jawa Timur',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Jahe merah pilihan dari kebun organik Malang. Dikeringkan dengan sempurna untuk mengunci khasiat dan aroma.',
    benefits: [
      'Menghangatkan badan',
      'Meningkatkan stamina',
      'Meredakan masuk angin',
      'Membantu sirkulasi darah',
    ],
    usage: 'Rebus 3-4 irisan jahe kering dengan 2 gelas air hingga mendidih. Saring dan minum hangat.',
    rating: 4.9,
    reviews: 89,
    stock: 30,
  },
  {
    id: '9',
    name: 'Ginseng Jawa Premium',
    price: 68000,
    image: 'https://images.unsplash.com/photo-1589968108222-c60eb6e4f817?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0b25na2F0JTIwYWxpJTIwcm9vdCUyMGdpbnNlbmd8ZW58MXx8fHwxNzY0NTYwNzQ3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'energy',
    farmer: {
      name: 'Pak Sugeng Riyanto',
      location: 'Dieng, Jawa Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Ginseng Jawa (Talinum) dari dataran tinggi Dieng. Dikenal sebagai penambah stamina dan vitalitas pria.',
    benefits: [
      'Meningkatkan stamina dan vitalitas',
      'Menambah tenaga fisik',
      'Meningkatkan libido',
      'Anti-aging alami',
    ],
    usage: 'Rebus 15-20 gram ginseng jawa kering dengan 3 gelas air hingga tersisa 1 gelas. Minum 1 kali sehari.',
    rating: 4.8,
    reviews: 112,
    stock: 20,
  },
  {
    id: '10',
    name: 'Pasak Bumi Kalimantan',
    price: 85000,
    image: 'https://images.unsplash.com/photo-1666370182138-1943009fae51?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxldXJ5Y29tYSUyMGxvbmdpZm9saWElMjByb290JTIwZHJpZWR8ZW58MXx8fHwxNzY0NTYwNzQ3fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'energy',
    farmer: {
      name: 'Pak Hasan Abdullah',
      location: 'Kalimantan Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Pasak Bumi asli Kalimantan, dikenal sebagai viagra alami Indonesia. Akar premium yang dipanen dari hutan.',
    benefits: [
      'Meningkatkan vitalitas pria',
      'Menambah stamina dan energi',
      'Meningkatkan kesuburan',
      'Menguatkan tulang dan otot',
    ],
    usage: 'Rebus 10 gram irisan pasak bumi dengan 4 gelas air hingga tersisa 2 gelas. Minum pagi dan sore.',
    rating: 4.9,
    reviews: 156,
    stock: 15,
  },
  {
    id: '11',
    name: 'Purwoceng Premium',
    price: 72000,
    image: 'https://images.unsplash.com/photo-1689682659750-197bbead0b27?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxwdXJ3b2NlbmclMjByb290JTIwZHJpZWR8ZW58MXx8fHwxNzY0NTYwOTE4fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'energy',
    farmer: {
      name: 'Pak Joko Susilo',
      location: 'Gunung Lawu, Jawa Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Purwoceng langka dari lereng Gunung Lawu. Tanaman afrodisiak alami yang hanya tumbuh di dataran tinggi Jawa.',
    benefits: [
      'Meningkatkan stamina dan daya tahan',
      'Afrodisiak alami kuat',
      'Mengatasi kelelahan kronis',
      'Meningkatkan kualitas tidur',
    ],
    usage: 'Seduh 5-10 gram purwoceng kering dengan air panas. Diamkan 10 menit, saring dan minum sebelum tidur.',
    rating: 4.7,
    reviews: 87,
    stock: 18,
  },
  {
    id: '12',
    name: 'Cabe Jawa Kering',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1639357870343-5d0c6df406a5?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsb25nJTIwcGVwcGVyJTIwcGlwZXIlMjBkcmllZHxlbnwxfHx8fDE3NjQ1NjA5MTh8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'energy',
    farmer: {
      name: 'Ibu Ningrum Sari',
      location: 'Lampung',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Cabe Jawa (Piper retrofractum) organik dari Lampung. Rempah hangat yang meningkatkan stamina dan menghangatkan tubuh.',
    benefits: [
      'Menghangatkan tubuh',
      'Meningkatkan stamina',
      'Melancarkan peredaran darah',
      'Mengatasi masuk angin',
    ],
    usage: 'Rebus 5-7 buah cabe jawa kering dengan 2 gelas air. Tambahkan madu, minum hangat 1-2 kali sehari.',
    rating: 4.6,
    reviews: 73,
    stock: 42,
  },

  // === KATEGORI DIGESTION (5 produk) ===
  {
    id: '4',
    name: 'Temulawak Bubuk',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1689682609878-971c0b1f86b1?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjdXJjdW1hJTIwdGVtdWxhd2FrJTIwcm9vdHxlbnwxfHx8fDE3NjQ1NjA3NDZ8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'digestion',
    farmer: {
      name: 'Pak Surya Wijaya',
      location: 'Solo, Jawa Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Temulawak asli dari Solo, diolah dengan standar kualitas tinggi. Baik untuk kesehatan hati dan pencernaan.',
    benefits: [
      'Menjaga kesehatan liver',
      'Meningkatkan nafsu makan',
      'Anti-inflamasi',
      'Meredakan masalah pencernaan',
    ],
    usage: 'Campurkan 1 sendok teh temulawak bubuk dengan madu dan air hangat. Minum pagi dan sore.',
    rating: 4.6,
    reviews: 78,
    stock: 40,
  },
  {
    id: '5',
    name: 'Kumis Kucing Kering',
    price: 32000,
    image: 'https://images.unsplash.com/photo-1572271909221-080855d974a2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjYXQlMjB3aGlza2VycyUyMHBsYW50JTIwb3J0aG9zaXBob258ZW58MXx8fHwxNzY0NTYwOTE5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'digestion',
    farmer: {
      name: 'Ibu Wulan Sari',
      location: 'Bandung, Jawa Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Kumis kucing organik dari Bandung. Terkenal untuk kesehatan ginjal dan saluran kemih.',
    benefits: [
      'Melancarkan buang air kecil',
      'Menjaga kesehatan ginjal',
      'Menurunkan asam urat',
      'Detoksifikasi alami',
    ],
    usage: 'Rebus 10-15 lembar daun kumis kucing kering dengan 2 gelas air. Minum airnya 2 kali sehari.',
    rating: 4.5,
    reviews: 92,
    stock: 60,
  },
  {
    id: '13',
    name: 'Sambung Nyawa Kering',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1764147057394-b71cb2c4e30c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxneW51cmElMjBwcm9jdW1iZW5zJTIwZ3JlZW4lMjBsZWF2ZXN8ZW58MXx8fHwxNzY0NTYwNzQ5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'digestion',
    farmer: {
      name: 'Ibu Aisyah Putri',
      location: 'Medan, Sumatera Utara',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Sambung nyawa organik dari Medan. Tanaman herbal multi-manfaat yang terkenal menurunkan tekanan darah dan kolesterol.',
    benefits: [
      'Menurunkan tekanan darah tinggi',
      'Menurunkan kolesterol',
      'Meningkatkan metabolisme',
      'Detoksifikasi tubuh',
    ],
    usage: 'Seduh 7-10 lembar daun sambung nyawa kering dengan air panas. Minum seperti teh 2 kali sehari.',
    rating: 4.6,
    reviews: 105,
    stock: 48,
  },
  {
    id: '14',
    name: 'Lidah Buaya Gel Kering',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1718857256152-137bce5bd17a?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhbG9lJTIwdmVyYSUyMGdlbCUyMHBsYW50fGVufDF8fHx8MTc2NDU2MDc0OXww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'digestion',
    farmer: {
      name: 'Pak Rudi Hartono',
      location: 'Pontianak, Kalimantan Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Gel lidah buaya organik yang dikeringkan untuk kemudahan penyimpanan. Kaya manfaat untuk pencernaan dan kulit.',
    benefits: [
      'Melancarkan pencernaan',
      'Mengatasi sembelit',
      'Detoksifikasi usus',
      'Menurunkan gula darah',
    ],
    usage: 'Larutkan 1 sendok teh gel lidah buaya kering dalam segelas air hangat. Minum pagi hari sebelum makan.',
    rating: 4.7,
    reviews: 119,
    stock: 38,
  },
  {
    id: '15',
    name: 'Pegagan Kering',
    price: 33000,
    image: 'https://images.unsplash.com/photo-1750437527283-2958f14e15ce?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjZW50ZWxsYSUyMGFzaWF0aWNhJTIwZ290dSUyMGtvbGF8ZW58MXx8fHwxNzY0NTYwNzQ5fDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'digestion',
    farmer: {
      name: 'Ibu Endang Lestari',
      location: 'Banyuwangi, Jawa Timur',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Pegagan (Centella asiatica) organik dari Banyuwangi. Dikenal sebagai herbal untuk kecerdasan dan kesehatan pencernaan.',
    benefits: [
      'Meningkatkan daya ingat dan konsentrasi',
      'Melancarkan peredaran darah',
      'Menyehatkan lambung',
      'Anti-aging dan regenerasi sel',
    ],
    usage: 'Seduh 1 sendok makan pegagan kering dengan air panas. Minum 2-3 kali sehari seperti teh herbal.',
    rating: 4.8,
    reviews: 134,
    stock: 55,
  },

  // === KATEGORI BEAUTY (5 produk) ===
  {
    id: '16',
    name: 'Bengkoang Bubuk Organik',
    price: 36000,
    image: 'https://images.unsplash.com/photo-1627785097735-35bab4fef733?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxqaWNhbWElMjB5YW0lMjBiZWFuJTIwd2hpdGV8ZW58MXx8fHwxNzY0NTYwMzExfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'beauty',
    farmer: {
      name: 'Ibu Dewi Anggraini',
      location: 'Garut, Jawa Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Bengkoang organik dari Garut yang diolah menjadi bubuk halus. Kaya vitamin C dan antioksidan untuk kulit cerah bercahaya.',
    benefits: [
      'Mencerahkan kulit wajah',
      'Menghilangkan flek hitam',
      'Mengecilkan pori-pori',
      'Melembabkan kulit',
    ],
    usage: 'Campurkan 2 sendok teh bengkoang bubuk dengan air atau yogurt sebagai masker wajah. Aplikasikan 2-3x seminggu.',
    rating: 4.8,
    reviews: 167,
    stock: 52,
  },
  {
    id: '17',
    name: 'Kunyit Putih Premium',
    price: 48000,
    image: 'https://images.unsplash.com/photo-1666370182138-1943009fae51?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx3aGl0ZSUyMHR1cm1lcmljJTIwcm9vdHxlbnwxfHx8fDE3NjQ1NjAzMTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'beauty',
    farmer: {
      name: 'Pak Darmawan Putra',
      location: 'Jogja',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Kunyit putih langka dari Jogja. Terkenal untuk kecantikan kulit dan kesehatan reproduksi wanita.',
    benefits: [
      'Mencerahkan kulit dari dalam',
      'Anti-aging kuat',
      'Menyehatkan organ kewanitaan',
      'Melancarkan haid',
    ],
    usage: 'Seduh 1/2 sendok teh kunyit putih bubuk dengan air hangat dan madu. Minum 1x sehari.',
    rating: 4.9,
    reviews: 142,
    stock: 28,
  },
  {
    id: '18',
    name: 'Kencur Kering Pilihan',
    price: 32000,
    image: 'https://images.unsplash.com/photo-1717769071502-e9b5d06c5fc2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxhcm9tYXRpYyUyMGdpbmdlciUyMGtlbmN1cnxlbnwxfHx8fDE3NjQ1NjAzMTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'beauty',
    farmer: {
      name: 'Ibu Sri Wahyuni',
      location: 'Blitar, Jawa Timur',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Kencur organik dari Blitar. Rempah tradisional untuk bau badan alami dan kesegaran tubuh.',
    benefits: [
      'Menghilangkan bau badan',
      'Menyegarkan tubuh',
      'Melancarkan haid',
      'Meningkatkan nafsu makan',
    ],
    usage: 'Rebus 10 gram kencur kering dengan 2 gelas air. Tambah madu dan asam, minum 2x sehari.',
    rating: 4.7,
    reviews: 98,
    stock: 45,
  },
  {
    id: '19',
    name: 'Daun Sirih Merah Kering',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1666672955594-5013913646b0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyZWQlMjBiZXRlbCUyMGxlYWYlMjBwaXBlcnxlbnwxfHx8fDE3NjQ1NjAzMTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'beauty',
    farmer: {
      name: 'Pak Agus Setiawan',
      location: 'Semarang, Jawa Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Daun sirih merah organik dari Semarang. Herbal kewanitaan terlengkap untuk kesehatan dan kecantikan.',
    benefits: [
      'Menjaga kesehatan organ kewanitaan',
      'Menghilangkan bau tidak sedap',
      'Mengencangkan kulit',
      'Antiseptik alami',
    ],
    usage: 'Rebus 7-10 lembar daun sirih merah dengan 3 gelas air untuk air cebok atau kumur. Bisa juga diminum.',
    rating: 4.8,
    reviews: 176,
    stock: 58,
  },
  {
    id: '20',
    name: 'Bunga Rosella Kering',
    price: 42000,
    image: 'https://images.unsplash.com/photo-1505572931516-e375f1a14d6b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxyb3NlbGxlJTIwaGliaXNjdXMlMjBmbG93ZXIlMjBkcmllZHxlbnwxfHx8fDE3NjQ1NjAzMTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'beauty',
    farmer: {
      name: 'Ibu Lina Marlina',
      location: 'Bogor, Jawa Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Bunga rosella organik dari Bogor. Kaya antioksidan dan vitamin C untuk kulit glowing dan tubuh sehat.',
    benefits: [
      'Mencerahkan kulit',
      'Menurunkan berat badan',
      'Kaya antioksidan',
      'Menurunkan kolesterol',
    ],
    usage: 'Seduh 5-7 bunga rosella kering dengan air panas seperti teh. Minum 2-3x sehari, bisa ditambah madu.',
    rating: 4.9,
    reviews: 203,
    stock: 65,
  },

  // === KATEGORI RELAXATION (4 produk) ===
  {
    id: '21',
    name: 'Lavender Kering Indonesia',
    price: 45000,
    image: 'https://images.unsplash.com/photo-1627716762987-d22098e86b3f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsYXZlbmRlciUyMGRyaWVkJTIwZmxvd2VycyUyMHB1cnBsZXxlbnwxfHx8fDE3NjQ1NjAzMTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'relaxation',
    farmer: {
      name: 'Pak Edi Hermawan',
      location: 'Bandungan, Jawa Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Lavender lokal dari dataran tinggi Bandungan. Aromanya menenangkan untuk relaksasi dan kualitas tidur lebih baik.',
    benefits: [
      'Menenangkan pikiran',
      'Meningkatkan kualitas tidur',
      'Mengurangi stress',
      'Aromaterapi alami',
    ],
    usage: 'Seduh sebagai teh atau gunakan sebagai aromaterapi dengan meletakkan di kamar tidur.',
    rating: 4.8,
    reviews: 145,
    stock: 40,
  },
  {
    id: '22',
    name: 'Serai Wangi Kering',
    price: 28000,
    image: 'https://images.unsplash.com/photo-1599574358415-57bbcc13d9a8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsZW1vbmdyYXNzJTIwc3RhbGtzJTIwZnJlc2h8ZW58MXx8fHwxNzY0NTYwMzExfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'relaxation',
    farmer: {
      name: 'Ibu Tuti Handayani',
      location: 'Bogor, Jawa Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Serai wangi organik dari Bogor dengan aroma segar menenangkan. Cocok untuk teh relaksasi.',
    benefits: [
      'Menenangkan saraf',
      'Melancarkan pencernaan',
      'Mengurangi kecemasan',
      'Aroma menyegarkan',
    ],
    usage: 'Seduh 2-3 batang serai kering dengan air panas. Minum hangat sebelum tidur.',
    rating: 4.6,
    reviews: 87,
    stock: 55,
  },
  {
    id: '23',
    name: 'Bunga Telang Kering',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1721903494397-e904fa3c7180?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxidXR0ZXJmbHklMjBwZWElMjBibHVlJTIwZmxvd2Vyc3xlbnwxfHx8fDE3NjQ1NjAzMTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'relaxation',
    farmer: {
      name: 'Pak Yusuf Rahman',
      location: 'Bali',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Bunga telang (butterfly pea) dari Bali dengan warna biru alami yang indah. Teh anti-stress dengan antioksidan tinggi.',
    benefits: [
      'Mengurangi stress dan kecemasan',
      'Antioksidan super tinggi',
      'Meningkatkan mood',
      'Menjaga kesehatan mata',
    ],
    usage: 'Seduh 8-10 bunga telang dengan air panas. Tambah lemon untuk warna ungu cantik. Minum 2x sehari.',
    rating: 4.9,
    reviews: 189,
    stock: 48,
  },
  {
    id: '24',
    name: 'Daun Mint Kering',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1621406251650-7990ec67100b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxmcmVzaCUyMG1pbnQlMjBsZWF2ZXMlMjBncmVlbnxlbnwxfHx8fDE3NjQ1NjAzMTF8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'relaxation',
    farmer: {
      name: 'Ibu Rina Kusuma',
      location: 'Malang, Jawa Timur',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Daun mint segar dari Malang yang dikeringkan dengan sempurna. Aroma mentol menyegarkan dan menenangkan.',
    benefits: [
      'Melegakan pernapasan',
      'Menenangkan saraf',
      'Mengurangi sakit kepala',
      'Melancarkan pencernaan',
    ],
    usage: 'Seduh 1 sendok makan daun mint kering dengan air panas. Minum 2-3x sehari atau gunakan aromaterapi.',
    rating: 4.7,
    reviews: 124,
    stock: 62,
  },

  // === KATEGORI RESPIRATORY (4 produk) ===
  {
    id: '25',
    name: 'Daun Sirih Hijau Kering',
    price: 30000,
    image: 'https://images.unsplash.com/photo-1654048210744-a82ee08e5fbf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxiZXRlbCUyMGxlYXZlcyUyMGdyZWVuJTIwcGlwZXJ8ZW58MXx8fHwxNzY0NTYwMzEyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'respiratory',
    farmer: {
      name: 'Pak Hadi Susanto',
      location: 'Jogja',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Daun sirih hijau organik dari Jogja. Antiseptik alami untuk kesehatan saluran pernapasan.',
    benefits: [
      'Melegakan pernapasan',
      'Mengobati batuk',
      'Antiseptik tenggorokan',
      'Mengatasi bau mulut',
    ],
    usage: 'Rebus 10-15 lembar daun sirih dengan 3 gelas air. Minum atau gunakan untuk berkumur.',
    rating: 4.7,
    reviews: 134,
    stock: 50,
  },
  {
    id: '26',
    name: 'Jeruk Nipis Kering',
    price: 34000,
    image: 'https://images.unsplash.com/photo-1760120067369-1e5138b8d3ab?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxsaW1lJTIwc2xpY2VzJTIwZHJpZWQlMjBjaXRydXN8ZW58MXx8fHwxNzY0NTYwMzEyfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'respiratory',
    farmer: {
      name: 'Pak Budi Cahyo',
      location: 'Pontianak, Kalimantan Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Irisan jeruk nipis kering dari Kalimantan. Kaya vitamin C untuk daya tahan tubuh dan pernapasan.',
    benefits: [
      'Meredakan batuk dan flu',
      'Meningkatkan imunitas',
      'Melegakan tenggorokan',
      'Kaya vitamin C',
    ],
    usage: 'Seduh 3-5 irisan jeruk nipis kering dengan air panas dan madu. Minum hangat 2-3x sehari.',
    rating: 4.6,
    reviews: 98,
    stock: 44,
  },
  {
    id: '27',
    name: 'Kayu Manis Kering',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1622798337764-259682f03741?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjaW5uYW1vbiUyMHN0aWNrcyUyMHNwaWNlfGVufDF8fHx8MTc2NDUwODM4M3ww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'respiratory',
    farmer: {
      name: 'Pak Ahmad Dahlan',
      location: 'Padang, Sumatera Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Kayu manis asli Padang dengan aroma khas. Menghangatkan dan melegakan pernapasan.',
    benefits: [
      'Melegakan pernapasan',
      'Menghangatkan tubuh',
      'Antibakteri alami',
      'Menurunkan gula darah',
    ],
    usage: 'Rebus 2-3 batang kayu manis dengan 2 gelas air. Tambah jahe dan madu, minum hangat.',
    rating: 4.8,
    reviews: 156,
    stock: 38,
  },
  {
    id: '28',
    name: 'Daun Saga Kering',
    price: 32000,
    image: 'https://images.unsplash.com/photo-1602943543714-cf535b048440?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZXJiYWwlMjBsZWF2ZXMlMjBtZWRpY2luZXxlbnwxfHx8fDE3MzI5MjM1NDd8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'respiratory',
    farmer: {
      name: 'Ibu Fatimah Zahra',
      location: 'Makassar, Sulawesi Selatan',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Daun saga organik dari Makassar. Herbal tradisional untuk batuk dan tenggorokan.',
    benefits: [
      'Meredakan batuk kering',
      'Melegakan tenggorokan',
      'Ekspektoran alami',
      'Anti-inflamasi',
    ],
    usage: 'Rebus 15-20 lembar daun saga dengan 3 gelas air hingga tersisa 1.5 gelas. Minum 2x sehari.',
    rating: 4.5,
    reviews: 76,
    stock: 41,
  },

  // === KATEGORI PAIN_RELIEF (3 produk) ===
  {
    id: '29',
    name: 'Lengkuas Merah Kering',
    price: 36000,
    image: 'https://images.unsplash.com/photo-1645865163176-cbc0459034c9?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxnYWxhbmdhbCUyMHJvb3QlMjByZWQlMjBnaW5nZXJ8ZW58MXx8fHwxNzY0NTYwMzEzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'pain_relief',
    farmer: {
      name: 'Pak Wahyu Hidayat',
      location: 'Tasikmalaya, Jawa Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Lengkuas merah organik dari Tasikmalaya. Anti-inflamasi kuat untuk mengatasi nyeri sendi dan otot.',
    benefits: [
      'Meredakan nyeri sendi',
      'Anti-inflamasi kuat',
      'Mengatasi rematik',
      'Melancarkan peredaran darah',
    ],
    usage: 'Rebus 15-20 gram lengkuas kering dengan 3 gelas air. Minum 2x sehari atau balurkan ke area nyeri.',
    rating: 4.7,
    reviews: 112,
    stock: 36,
  },
  {
    id: '30',
    name: 'Daun Beluntas Kering',
    price: 33000,
    image: 'https://images.unsplash.com/photo-1627323678334-3a5d164b0e24?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxoZXJiJTIwbGVhdmVzfGVufDF8fHx8MTczMjkyMzU0N3ww&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'pain_relief',
    farmer: {
      name: 'Ibu Hasanah',
      location: 'Cirebon, Jawa Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Daun beluntas organik dari Cirebon. Herbal tradisional untuk mengatasi bau badan dan nyeri haid.',
    benefits: [
      'Meredakan nyeri haid',
      'Menghilangkan bau badan',
      'Menurunkan demam',
      'Melancarkan haid',
    ],
    usage: 'Seduh 10-12 lembar daun beluntas dengan air panas. Minum 2x sehari saat haid atau sesuai kebutuhan.',
    rating: 4.6,
    reviews: 89,
    stock: 47,
  },
  {
    id: '31',
    name: 'Asam Jawa Kering',
    price: 28000,
    image: 'https://images.unsplash.com/photo-1762608292626-a384d1cc401f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0YW1hcmluZCUyMGZydWl0JTIwYnJvd24lMjBwb2R8ZW58MXx8fHwxNzY0NTYwMzEzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'pain_relief',
    farmer: {
      name: 'Pak Kohar Ibrahim',
      location: 'Indramayu, Jawa Barat',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Asam jawa matang dari Indramayu. Kaya antioksidan dan vitamin untuk kesehatan pencernaan dan meredakan nyeri.',
    benefits: [
      'Meredakan sakit perut',
      'Melancarkan pencernaan',
      'Menurunkan demam',
      'Detoksifikasi tubuh',
    ],
    usage: 'Rendam 2 sendok asam jawa dengan air hangat. Saring dan minum airnya, bisa ditambah gula aren.',
    rating: 4.5,
    reviews: 95,
    stock: 58,
  },

  // === KATEGORI DIABETES (3 produk) ===
  {
    id: '32',
    name: 'Daun Insulin Kering',
    price: 40000,
    image: 'https://images.unsplash.com/photo-1686186149718-2c1ddad5d19e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxjb3N0dXMlMjBpbnN1bGluJTIwcGxhbnQlMjBsZWF2ZXN8ZW58MXx8fHwxNzY0NTYwMzEzfDA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'diabetes',
    farmer: {
      name: 'Pak Bejo Santoso',
      location: 'Surakarta, Jawa Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Daun insulin organik dari Surakarta. Herbal ampuh untuk mengontrol gula darah secara alami.',
    benefits: [
      'Menurunkan gula darah',
      'Meningkatkan sensitivitas insulin',
      'Mencegah komplikasi diabetes',
      'Mengontrol kadar gula stabil',
    ],
    usage: 'Seduh 5-7 lembar daun insulin dengan air panas. Minum seperti teh 2-3x sehari sebelum makan.',
    rating: 4.8,
    reviews: 167,
    stock: 32,
  },
  {
    id: '33',
    name: 'Kayu Secang Kering',
    price: 35000,
    image: 'https://images.unsplash.com/photo-1700654334430-880fa9d255bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxzYXBwYW53b29kJTIwcmVkJTIwd29vZCUyMHN0aWNrc3xlbnwxfHx8fDE3NjQ1NjAzMTN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'diabetes',
    farmer: {
      name: 'Pak Ismail Marzuki',
      location: 'Semarang, Jawa Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Kayu secang asli Semarang dengan warna merah alami. Antioksidan tinggi untuk diabetes dan kesehatan jantung.',
    benefits: [
      'Menurunkan gula darah',
      'Antioksidan tinggi',
      'Menjaga kesehatan jantung',
      'Meningkatkan imunitas',
    ],
    usage: 'Rebus 15-20 gram kayu secang dengan 3 gelas air hingga berwarna merah. Minum 2x sehari.',
    rating: 4.7,
    reviews: 143,
    stock: 45,
  },
  {
    id: '34',
    name: 'Brotowali Kering',
    price: 38000,
    image: 'https://images.unsplash.com/photo-1602170284446-3b2b50aba96f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHx0aW5vc3BvcmElMjBjb3JkaWZvbGlhJTIwYml0dGVyJTIwdmluZXxlbnwxfHx8fDE3NjQ1NjAzMTN8MA&ixlib=rb-4.1.0&q=80&w=1080',
    category: 'diabetes',
    farmer: {
      name: 'Ibu Diah Permata',
      location: 'Purwokerto, Jawa Tengah',
      photo: 'https://images.unsplash.com/photo-1602511706963-02ecf61637b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=M3w3Nzg4Nzd8MHwxfHNlYXJjaHwxfHxJbmRvbmVzaWFuJTIwZmFybWVyJTIwZmllbGR8ZW58MXx8fHwxNzYwNjcyMDI2fDA&ixlib=rb-4.1.0&q=80&w=1080',
    },
    description: 'Brotowali organik dari Purwokerto. Herbal pahit yang ampuh untuk diabetes dan demam.',
    benefits: [
      'Menurunkan gula darah tinggi',
      'Menurunkan demam',
      'Meningkatkan imunitas',
      'Detoksifikasi hati',
    ],
    usage: 'Rebus 10-15 cm batang brotowali dengan 3 gelas air. Minum 2x sehari, bisa ditambah madu.',
    rating: 4.6,
    reviews: 128,
    stock: 29,
  },
];

export const mockOrders: Order[] = [
  {
    id: 'ORD001',
    productName: 'Kunyit Bubuk Organik - 250g',
    quantity: 2,
    total: 70000,
    customerName: 'Ibu Rina Kusuma',
    customerAddress: 'Jl. Sudirman No. 45, Jakarta Selatan',
    status: 'new',
    date: '2025-10-17',
  },
  {
    id: 'ORD002',
    productName: 'Jahe Merah Kering - 200g',
    quantity: 1,
    total: 45000,
    customerName: 'Bapak Andi Wijaya',
    customerAddress: 'Jl. Gatot Subroto 78, Jakarta Pusat',
    status: 'new',
    date: '2025-10-17',
  },
  {
    id: 'ORD003',
    productName: 'Daun Kelor Kering - 100g',
    quantity: 3,
    total: 84000,
    customerName: 'Ibu Maya Sari',
    customerAddress: 'Jl. Asia Afrika 12, Bandung',
    status: 'accepted',
    date: '2025-10-16',
  },
  {
    id: 'ORD004',
    productName: 'Temulawak Bubuk - 150g',
    quantity: 1,
    total: 38000,
    customerName: 'Pak Rudi Hartono',
    customerAddress: 'Jl. Malioboro 90, Yogyakarta',
    status: 'preparing',
    date: '2025-10-15',
  },
];
