/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "sisrsmlwmyovwhwymrqp"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNpc3JzbWx3bXlvdndod3ltcnFwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA5MTIxMDksImV4cCI6MjA3NjQ4ODEwOX0.mk_-q822kDJCSdtvbJW0mjTot31WuJ7nC_zpJM-2DRc"